language: node_js

node_js:
  - 4
  - 5
  - 6

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - yarn install

script:
  - npm test

after_success:
  - npm run cover

notifications:
  email:
    - sergiofilhow@gmail.com
