language: node_js

node_js:
  - 9

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - npm install typescript -g
  - yarn

script:
  - yarn test

after_success:
  - npm run cover

notifications:
  email:
    - sergiofilhow@gmail.com
